name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: What steps did you take to encounter this bug?
      placeholder: Tell us what you see!
      value: |
        1.
    validations:
      required: true
  - type: input
    attributes:
      label: Reproduction link
      description: A StackBlitz/CodePen/CodeSandbox reproduction link
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
      placeholder: Tell us what you expected to see!
      value: |
        I expected
    validations:
        required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: textarea
    attributes:
      label: More details
      description: >-
        Is there anything else we should know?
