name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]"
labels: ["enhancement", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature for this project!
        Please fill out the sections below to help us understand your request.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the feature is.
      placeholder: I'd like to see...
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide any additional details or context for the feature.
      placeholder: I think this feature would be useful because...
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also thought about...
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information or screenshots about the feature request here.
      placeholder: Here's a screenshot...
